### ISSUE TITLE
[Written for SuperSajuuk} - Auto response

### ISSUE THREAD

**Issue by Kitty-Therapist** [Dougley/MBv2#69]
**Is your feature request related to a problem? Please describe.**
Custodians have been posting "report latest" without any additional context, which would end up having the other Custodians instantly responding to report the suggestion even if the latest ends up being 2nd latest.
**Describe the solution you'd like**
If a Custodian comments "report latest", MegaBot could have an auto responder that would say the following; hey, why are you asking custodians to report that? Provide context (ie a message link or feedback post link) with a reason in future :dabHeart:. Which will then prompt them to comment in the future. 
**Additional context**
I wrote this for Sajuuk, but I can't help but to be concerned about the false positives so I'm unsure of how well it would work out. Alternately, we could make an announcement to remind the Custodians to add context so people will know.

**Comment by blastoise186** [comment]
In my personal view, I can see a few problems with this, which may affect the practicality of this feature request.

My first problem is the fact that both false triggers and valid triggers could start to spam the channels, particularly for users who have full alerts enabled - which may result in sending out more alerts which are of little value to them. This is mitigated by the fact DFeedback has over 2,500 members which limits how many alerts get sent to Mobile, but this doesn't apply to Desktop.

I also note that since DFeedback opened, the words "Report Latest" only come up on server search 360 times across every channel that I can see at the time of writing and it does seem to also count the use of the :report: Emoji, as shown here:

![image](https://user-images.githubusercontent.com/40033667/54050295-beb74780-41d6-11e9-9c01-30b9f5b7d54f.png)

I'm also not too keen on bots responding to anything that isn't an explicit command in general, except for specific cases such as AutoMod features or where such responses are part of the core features in the relevant bot.

There's also the issues with false triggers - I feel that if MegaBot fired off random messages for no obvious reason just because a trigger word was in someone's message, it might become more irritating than helpful. I also don't feel it's appropriate for a copy/pasted reply is right for asking someone to explain their reasons - a handwritten message is more effective in my experience.

While some of those might be made less problematic by having the message autopurge after a while, it wouldn't solve the problem that a bunch of users have already had unneeded alerts broadcast to them.

However, possibly the biggest problem is that there's not really an easy way to ensure such a message can _correctly_ trigger on all possible variants of not just "report latest" but also any other messages that one of us might say which refers to reporting the latest suggestion - "report?", "latest?", "should we report that?" and a huge number of other possibilities which could become difficult to maintain.

Overall, I feel that making an announcement will help let everyone know, but I don't see much value of simply trying to automate the reminders.

**Comment by Dougley** [comment]
Saying "report latest" indirectly tells you to navigate to the feed to report the submission, adding an extra embed that people might or might not read is trivial.

Additionally, autoresponders goes against the structure of the command system, everything must be invoked with a prefix.

Autoreponders bring additional issues like people invoking them on accident, since "report latest" is such a well used term in the server 

Say this functionality was a command (eg. `!latest`) instead of an autorepond to fix the command system issue, wouldn't we create a shortcut for `!info <id>`?
